server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment-saga?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  cloud:
    function:
      definition: paymentProcessor
    stream:
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event